version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependency-updates:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"
    open-pull-requests-limit: 1

  - package-ecosystem: "npm"
    directory: "/nodejs-package"
    schedule:
      interval: "weekly"
    groups:
      dependency-updates:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"
    open-pull-requests-limit: 1

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-updates:
        patterns:
          - "*"
