import { createContext, useContext, useEffect, useState } from "react";
import type { ReactNode } from "react";

export type LanguageCode = "en" | "vi" | "zh" | "ja" | "no" | "es" | "fr" | "ko";

export interface Language {
  code: LanguageCode;
  label: string;
}

export const languages: Language[] = [
  { code: "en", label: "English" },
  { code: "vi", label: "Tiếng Việt" },
  { code: "zh", label: "中文" },
  { code: "ja", label: "日本語" },
  { code: "no", label: "Norsk" },
  { code: "es", label: "Español" },
  { code: "fr", label: "Français" },
  { code: "ko", label: "한국어" },
];

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    appName: "Markdown Them",
    tagline: "Convert from DOCX, DOC, PDF, HTML, XLSX, XLS, XLM, PPTX, ODT, ODP, ODS, RTF, and text files to readable markdown. Note: Legacy formats (.doc, .xls, .xlm) use renaming emulation and sometimes will not work correctly.",
    files: "Files",
    text: "Text",
    privacyFirst: "Privacy-first",
    privacyFirstDetail: "No account, no file tracking, no telemetry",
    localProcessingDesktop: "100% local processing",
    localProcessingDesktopDetail: "Runs on this computer",
    localProcessingBrowser: "100% client-side conversion",
    localProcessingBrowserDetail: "Runs only inside your browser, and only converting processes",
    noUploads: "No document uploads",
    noUploadsDetail: "Files never leave your device, no one can get your files",
    selection: "Selection",
    clear: "Clear",
    selected: "selected",
    done: "done",
    failed: "failed",
    outputFolder: "Output folder",
    sameFolder: "Same folder as source",
    chooseOutput: "Choose output folder",
    useSourceFolders: "Use source folders",
    folders: "Folders",
    convert: "Convert",
    output: "Output",
    downloadAll: "Download all",
    noFilesSelected: "No files selected",
    download: "Download",
    pending: "pending",
    input: "Input",
    markdown: "Markdown",
    copy: "Copy",
    save: "Save",
    madeBy: "made by",
    githubRepo: "Open source - GitHub repo",
    variants: "Other variants",
    webApp: "Web application",
    webAppVariantDetail: "Open the browser version on GitHub Pages.",
    desktopApp: "Desktop application",
    desktopApplication: "Desktop application",
    desktopVariantDetail: "Open releases and choose the Windows, macOS, or Linux file for your device.",
    openVsxVariantDetail: "Install in Open VSX-compatible editors.",
    vscodeMarketplace: "VS Code Marketplace",
    vscodeMarketplaceVariantDetail: "Install directly in Visual Studio Code.",
    npmPackage: "npm package",
    npmPackageVariantDetail: "Use the Node.js package in scripts or apps.",
    updateAvailable: "Update available",
    mitLicense: "MIT license",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    backToConverter: "Back to converter",
    returnToConverter: "Return to Converter",
    lastUpdated: "Last Updated: June 2026",
    copiedNotice: "Copied",
    savedNotice: "Saved",
    privacyNoticeHeader: "100% Client-Side & Local Processing",
    privacyNoticeText: "Markdown Them is engineered to run entirely on your local device. We never upload your files, track your data, or transmit information to external servers.",
    privacySec1Title: "1. Information We Collect",
    privacySec1Intro: "We believe that your data is yours alone. Because of this:",
    noFileCollection: "No File Collection",
    noFileCollectionDetail: "When you convert documents (DOCX, PDF, HTML, XLSX, PPTX, etc.) or text to Markdown, all processing is performed locally inside your web browser or local computer. Your files never leave your device.",
    noPersonalData: "No Personal Data",
    noPersonalDataDetail: "We do not require account creation, registration, or sign-up. We do not collect names, email addresses, or any other identifying information.",
    noTelemetry: "No Telemetry or Tracking",
    noTelemetryDetail: "The application does not contain tracking scripts, analytics tools, or cookies to track your behavior.",
    privacySec2Title: "2. Storage of Settings",
    privacySec2Text: "To provide a seamless experience, we store user preferences (such as your preferred color theme) locally in your browser's localStorage. This data remains on your machine and is never synchronized with any external service. You can clear this data at any time by clearing your browser's storage.",
    privacySec3Title: "3. Third-Party Websites and Services",
    privacySec3Text: "Our application may link to external websites such as GitHub or npm. These external sites are not operated by us and have their own privacy policies. We advise you to review the privacy policy of any third-party websites you visit.",
    privacySec4Title: "4. Changes to This Privacy Policy",
    privacySec4Text: "We may update our Privacy Policy from time to time. Any changes will be posted on this page with an updated revision date.",
    privacySec5Title: "5. Contact Us",
    privacySec5Text: "If you have any questions or suggestions regarding our Privacy Policy, please feel free to reach out to us on our project repository.",
    termsNoticeHeader: "Open Source under the MIT License",
    termsNoticeText: "Markdown Them is completely open source. You are free to use, modify, and distribute this software in accordance with the MIT License terms.",
    termsSec1Title: "1. Acceptance of Terms",
    termsSec1Text: "By accessing or using the Markdown Them web application or desktop application, you agree to be bound by these Terms of Service. If you do not agree to all of the terms and conditions, do not use the application.",
    termsSec2Title: "2. License and Permitted Use",
    termsSec2Intro: "Markdown Them is licensed under the terms of the MIT License. You are granted permission to:",
    termsSec2Item1: "Use the software for commercial or personal projects.",
    termsSec2Item2: "Modify, distribute, and sublicense copies of the software.",
    termsSec2Item3: "Include the software in other packages or distributions.",
    termsSec2Outro: "The only requirement is that the copyright notice and license notice must be included in all copies or substantial portions of the Software.",
    termsSec3Title: "3. Local Processing Limitation",
    termsSec3Text: "Markdown Them is designed as a client-side converter tool. It is provided \"as is\", intended for offline/local use. You are solely responsible for ensuring the safety and integrity of the files you import into the converter.",
    termsSec4Title: "4. Warranty Disclaimer",
    termsSec4Text: "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.",
    termsSec5Title: "5. Changes to the Terms",
    termsSec5Text: "We reserve the right, at our sole discretion, to modify or replace these Terms at any time. It is your responsibility to check these Terms periodically for changes.",
  },
  vi: {
    appName: "Markdown Them",
    tagline: "Chuyển đổi các tệp DOCX, DOC, PDF, HTML, XLSX, XLS, XLM, PPTX, ODT, ODP, ODS, RTF và văn bản sang định dạng markdown dễ đọc. Lưu ý: Các định dạng cũ (.doc, .xls, .xlm) sử dụng giả lập đổi tên và đôi khi hoạt động không chính xác.",
    files: "Tệp tin",
    text: "Văn bản",
    privacyFirst: "Quyền riêng tư hàng đầu",
    privacyFirstDetail: "Không tài khoản, không theo dõi tệp, không đo lường dữ liệu",
    localProcessingDesktop: "Xử lý 100% cục bộ",
    localProcessingDesktopDetail: "Chạy trên máy tính này",
    localProcessingBrowser: "Chuyển đổi 100% phía máy khách",
    localProcessingBrowserDetail: "Chỉ chạy trong trình duyệt của bạn, quy trình chuyển đổi nội bộ",
    noUploads: "Không tải tệp lên máy chủ",
    noUploadsDetail: "Tệp không bao giờ rời khỏi thiết bị của bạn, bảo mật tuyệt đối",
    selection: "Lựa chọn",
    clear: "Xóa",
    selected: "đã chọn",
    done: "hoàn thành",
    failed: "thất bại",
    outputFolder: "Thư mục đầu ra",
    sameFolder: "Cùng thư mục với nguồn",
    chooseOutput: "Chọn thư mục đầu ra",
    useSourceFolders: "Sử dụng thư mục nguồn",
    folders: "Thư mục",
    convert: "Chuyển đổi",
    output: "Kết quả đầu ra",
    downloadAll: "Tải xuống tất cả",
    noFilesSelected: "Chưa chọn tệp tin nào",
    download: "Tải xuống",
    pending: "đang chờ",
    input: "Đầu vào",
    markdown: "Markdown",
    copy: "Sao chép",
    save: "Lưu lại",
    madeBy: "phát triển bởi",
    githubRepo: "Mã nguồn mở - Kho lưu trữ GitHub",
    variants: "Các biến thể khác",
    webApp: "Ứng dụng web",
    webAppVariantDetail: "Mở phiên bản trình duyệt trên GitHub Pages.",
    desktopApp: "Ứng dụng máy tính",
    desktopApplication: "Ứng dụng máy tính",
    desktopVariantDetail: "Mở trang phát hành và chọn tệp Windows, macOS hoặc Linux phù hợp với thiết bị của bạn.",
    openVsxVariantDetail: "Cài đặt trong các trình chỉnh sửa tương thích Open VSX.",
    vscodeMarketplace: "VS Code Marketplace",
    vscodeMarketplaceVariantDetail: "Cài đặt trực tiếp trong Visual Studio Code.",
    npmPackage: "Gói npm",
    npmPackageVariantDetail: "Dùng gói Node.js trong script hoặc ứng dụng.",
    updateAvailable: "Có bản cập nhật",
    mitLicense: "Giấy phép MIT",
    privacyPolicy: "Chính sách bảo mật",
    termsOfService: "Điều khoản dịch vụ",
    backToConverter: "Quay lại công cụ chuyển đổi",
    returnToConverter: "Trở về công cụ chuyển đổi",
    lastUpdated: "Cập nhật lần cuối: Tháng 6 năm 2026",
    copiedNotice: "Đã sao chép",
    savedNotice: "Đã lưu",
    privacyNoticeHeader: "Xử lý 100% phía máy khách & cục bộ",
    privacyNoticeText: "Markdown Them được thiết kế để chạy hoàn toàn trên thiết bị cục bộ của bạn. Chúng tôi không bao giờ tải lên tệp của bạn, theo dõi dữ liệu của bạn hoặc truyền thông tin đến các máy chủ bên ngoài.",
    privacySec1Title: "1. Thông tin chúng tôi thu thập",
    privacySec1Intro: "Chúng tôi tin rằng dữ liệu là của riêng bạn. Vì lý do đó:",
    noFileCollection: "Không thu thập tệp",
    noFileCollectionDetail: "Khi bạn chuyển đổi tài liệu hoặc văn bản sang Markdown, mọi hoạt động xử lý được thực hiện cục bộ trong trình duyệt web hoặc máy tính của bạn. Tệp của bạn không bao giờ rời khỏi thiết bị.",
    noPersonalData: "Không có dữ liệu cá nhân",
    noPersonalDataDetail: "Chúng tôi không yêu cầu tạo tài khoản hay đăng ký. Chúng tôi không thu thập tên, địa chỉ email hay bất kỳ thông tin nhận dạng nào khác.",
    noTelemetry: "Không có đo lường hoặc theo dõi",
    noTelemetryDetail: "Ứng dụng không chứa mã theo dõi, công cụ phân tích hoặc cookie để theo dõi hành vi của bạn.",
    privacySec2Title: "2. Lưu trữ cài đặt",
    privacySec2Text: "Để cung cấp trải nghiệm liền mạch, chúng tôi lưu trữ các tùy chọn của người dùng (như chủ đề màu sắc) cục bộ trong localStorage của trình duyệt. Dữ liệu này chỉ nằm trên máy của bạn và không bao giờ được đồng bộ hóa với bất kỳ dịch vụ bên ngoài nào. Bạn có thể xóa dữ liệu này bất cứ lúc nào bằng cách xóa bộ nhớ trình duyệt.",
    privacySec3Title: "3. Các trang web và dịch vụ của bên thứ ba",
    privacySec3Text: "Ứng dụng của chúng tôi có thể liên kết đến các trang web bên ngoài như GitHub hoặc npm. Những trang này không do chúng tôi vận hành và có chính sách bảo mật riêng. Bạn nên xem xét chính sách bảo mật của bất kỳ trang web bên thứ ba nào bạn truy cập.",
    privacySec4Title: "4. Thay đổi đối với Chính sách bảo mật này",
    privacySec4Text: "Chúng tôi có thể cập nhật Chính sách bảo mật của mình theo thời gian. Mọi thay đổi sẽ được công bố trên trang này với ngày cập nhật mới nhất.",
    privacySec5Title: "5. Liên hệ với chúng tôi",
    privacySec5Text: "Nếu bạn có bất kỳ câu hỏi hoặc đề xuất nào liên quan đến Chính sách bảo mật của chúng tôi, vui lòng liên hệ qua kho lưu trữ dự án của chúng tôi.",
    termsNoticeHeader: "Mã nguồn mở theo Giấy phép MIT",
    termsNoticeText: "Markdown Them hoàn toàn là mã nguồn mở. Bạn có thể tự do sử dụng, sửa đổi và phân phối phần mềm này theo các điều khoản của Giấy phép MIT.",
    termsSec1Title: "1. Chấp nhận các điều khoản",
    termsSec1Text: "Bằng cách truy cập hoặc sử dụng ứng dụng web hoặc ứng dụng máy tính Markdown Them, bạn đồng ý tuân thủ các Điều khoản dịch vụ này. Nếu bạn không đồng ý với tất cả điều khoản, vui lòng không sử dụng ứng dụng.",
    termsSec2Title: "2. Giấy phép và Mục đích sử dụng được phép",
    termsSec2Intro: "Markdown Them được cấp phép theo các điều khoản của Giấy phép MIT. Bạn được phép:",
    termsSec2Item1: "Sử dụng phần mềm cho các dự án thương mại hoặc cá nhân.",
    termsSec2Item2: "Sửa đổi, phân phối và cấp phép lại các bản sao của phần mềm.",
    termsSec2Item3: "Đưa phần mềm vào các gói hoặc bản phân phối khác.",
    termsSec2Outro: "Yêu cầu duy nhất là thông báo bản quyền và thông báo giấy phép phải được đính kèm trong tất cả các bản sao hoặc phần quan trọng của Phần mềm.",
    termsSec3Title: "3. Giới hạn xử lý cục bộ",
    termsSec3Text: "Markdown Them được thiết kế như một công cụ chuyển đổi phía máy khách. Nó được cung cấp \"như hiện tại\", nhằm sử dụng ngoại tuyến/cục bộ. Bạn hoàn toàn chịu trách nhiệm đảm bảo tính an sau và toàn vẹn của các tệp bạn nhập vào công cụ.",
    termsSec4Title: "4. Tuyên bố từ chối bảo hành",
    termsSec4Text: "PHẦN MỀM ĐƯỢC CUNG CẤP \"NHƯ HIỆN TẠI\", KHÔNG CÓ BẤT KỲ BẢO HÀNH NÀO, DÙ TUYÊN BỐ HAY NGỤ Ý. TRONG MỌI TRƯỜNG HỢP, CÁC TÁC GIẢ HOẶC CHỦ SỞ HỮU BẢN QUYỀN SẼ KHÔNG CHỊU TRÁCH NHIỆM PHÁP LÝ ĐỐI VỚI BẤT KỲ KHIẾU NẠI, THIỆT HẠI HOẶC TRÁCH NHIỆM PHÁP LÝ NÀO KHÁC PHÁT SINH TỪ, NGOÀI HOẶC LIÊN QUAN ĐẾN PHẦN MỀM HOẶC VIỆC SỬ DỤNG PHẦN MỀM.",
    termsSec5Title: "5. Thay đổi điều khoản",
    termsSec5Text: "Chúng tôi có quyền, theo quyết định riêng của mình, sửa đổi hoặc thay thế các Điều khoản này bất kỳ lúc nào. Bạn có trách nhiệm kiểm tra các Điều khoản này định kỳ để biết các thay đổi.",
  },
  zh: {
    appName: "Markdown Them",
    tagline: "将 DOCX, DOC, PDF, HTML, XLSX, XLS, XLM, PPTX, ODT, ODP, ODS, RTF 和文本文件转换为易读的 markdown 格式。注意：旧版格式（.doc, .xls, .xlm）使用重命名模拟，有时可能无法正确转换。",
    files: "文件",
    text: "文本",
    privacyFirst: "隐私第一",
    privacyFirstDetail: "免账户、无文件追踪、无遥测数据",
    localProcessingDesktop: "100% 本地处理",
    localProcessingDesktopDetail: "在本机上运行",
    localProcessingBrowser: "100% 客户端转换",
    localProcessingBrowserDetail: "仅在您的浏览器中运行，且仅进行转换处理",
    noUploads: "无需上传文件",
    noUploadsDetail: "文件绝不离开您的设备，没人能获取您的文件",
    selection: "选择",
    clear: "清空",
    selected: "已选择",
    done: "完成",
    failed: "失败",
    outputFolder: "输出文件夹",
    sameFolder: "与源文件相同文件夹",
    chooseOutput: "选择输出文件夹",
    useSourceFolders: "使用源文件夹",
    folders: "文件夹",
    convert: "转换",
    output: "输出结果",
    downloadAll: "下载全部",
    noFilesSelected: "未选择文件",
    download: "下载",
    pending: "等待中",
    input: "输入",
    markdown: "Markdown",
    copy: "复制",
    save: "保存",
    madeBy: "由...制作",
    githubRepo: "开源 - GitHub 仓库",
    variants: "其他版本",
    webApp: "Web 应用",
    webAppVariantDetail: "在 GitHub Pages 上打开浏览器版本。",
    desktopApp: "桌面应用",
    desktopApplication: "桌面应用",
    desktopVariantDetail: "打开发布页面，并选择适合你设备的 Windows、macOS 或 Linux 文件。",
    openVsxVariantDetail: "在兼容 Open VSX 的编辑器中安装。",
    vscodeMarketplace: "VS Code Marketplace",
    vscodeMarketplaceVariantDetail: "直接在 Visual Studio Code 中安装。",
    npmPackage: "npm 软件包",
    npmPackageVariantDetail: "在脚本或应用中使用 Node.js 包。",
    updateAvailable: "有可用更新",
    mitLicense: "MIT 许可证",
    privacyPolicy: "隐私政策",
    termsOfService: "服务条款",
    backToConverter: "返回转换器",
    returnToConverter: "返回转换器",
    lastUpdated: "最近更新：2026年6月",
    copiedNotice: "已复制",
    savedNotice: "已保存",
    privacyNoticeHeader: "100% 客户端与本地处理",
    privacyNoticeText: "Markdown Them 旨在完全在您的本地设备上运行。我们绝不上传您的文件、追踪您的数据，或将信息传输到外部服务器。",
    privacySec1Title: "1. 我们收集的信息",
    privacySec1Intro: "我们相信您的数据只属于您。因此：",
    noFileCollection: "无文件收集",
    noFileCollectionDetail: "当您将文档（DOCX, PDF, HTML, XLSX, PPTX, 等）或文本转换为 Markdown 时，所有处理都在您的浏览器或本地计算机上完成。您的文件永远不会离开您的设备。",
    noPersonalData: "无个人数据",
    noPersonalDataDetail: "我们不需要创建账户、注册或登录。我们不收集您的姓名、电子邮件地址或任何其他个人身份信息。",
    noTelemetry: "无遥测与追踪",
    noTelemetryDetail: "本应用不包含任何用于追踪您行为的追踪脚本、分析工具或 cookie。",
    privacySec2Title: "2. 设置的存储",
    privacySec2Text: "为了提供无缝体验，我们会将您的用户偏好（如主题颜色）本地存储在浏览器的 localStorage 中。这些数据只保存在您的机器上，绝不会同步到外部服务。您可以通过清除浏览器存储来随时清空这些数据。",
    privacySec3Title: "3. 第三方网站与服务",
    privacySec3Text: "我们的应用可能会包含指向外部网站（如 GitHub 或 npm）的链接。这些外部网站不由我们运营，并且它们拥有各自的隐私政策。我们建议您在访问任何第三方网站时仔细阅读其隐私政策。",
    privacySec4Title: "4. 本隐私政策的变更",
    privacySec4Text: "我们可能会不时更新我们的隐私政策。任何更改都将发布在此页面上，并更新最新修改日期。",
    privacySec5Title: "5. 联系我们",
    privacySec5Text: "如果您对我们的隐私政策有任何疑问或建议，请随时在我们的项目仓库中向我们提出。",
    termsNoticeHeader: "基于 MIT 许可证开源",
    termsNoticeText: "Markdown Them 完全开源。您可以根据 MIT 许可证条款自由地使用、修改和分发本软件。",
    termsSec1Title: "1. 接受条款",
    termsSec1Text: "访问或使用 Markdown Them 网页版或桌面版应用，即表示您同意受这些服务条款的约束。如果您不同意所有条款和条件，请勿使用本应用。",
    termsSec2Title: "2. 许可与许可范围",
    termsSec2Intro: "Markdown Them 基于 MIT 许可证授权。您被授予以下许可：",
    termsSec2Item1: "将软件用于商业或个人项目。",
    termsSec2Item2: "修改、分发软件副本以及进行二次授权。",
    termsSec2Item3: "将软件包含在其他软件包或发行版中。",
    termsSec2Outro: "唯一的限制是，软件的所有副本或主要部分都必须包含版权声明和许可证声明。",
    termsSec3Title: "3. 本地处理限制",
    termsSec3Text: "Markdown Them 被设计为客户端转换工具，按“原样”提供，仅供离线/本地使用。您将独立承担确保导入转换器的文件安全和完整性的全部责任。",
    termsSec4Title: "4. 免责声明",
    termsSec4Text: "本软件按“原样”提供，不提供任何明示或暗示的保证，包括但不限于对适销性、特定用途的适用性和非侵权性的保证。在任何情况下，作者或版权所有者均不对任何索赔、损害或其他责任负责。",
    termsSec5Title: "5. 条款的变更",
    termsSec5Text: "我们保留根据自身判定随时修改或替换这些条款的权利。您有责任定期检查这些条款以了解最新变更。",
  },
  ja: {
    appName: "Markdown Them",
    tagline: "DOCX, DOC, PDF, HTML, XLSX, XLS, XLM, PPTX, ODT, ODP, ODS, RTF、およびテキストファイルを読みやすい markdown に変換します。注意：レガシーフォーマット（.doc, .xls, .xlm）は名前変更エミュレーションを使用するため、正しく変換されない場合があります。",
    files: "ファイル",
    text: "テキスト",
    privacyFirst: "プライバシー第一",
    privacyFirstDetail: "アカウント不要、ファイル追跡なし、テレメトリなし",
    localProcessingDesktop: "100% ローカル処理",
    localProcessingDesktopDetail: "このコンピューター上で実行",
    localProcessingBrowser: "100% クライアント側変換",
    localProcessingBrowserDetail: "ブラウザ内のみで動作し、変換プロセスのみを実行",
    noUploads: "ファイルのアップロードなし",
    noUploadsDetail: "ファイルはデバイスから離れず、誰もあなたのファイルを取得できません",
    selection: "選択",
    clear: "クリア",
    selected: "選択済み",
    done: "完了",
    failed: "失敗",
    outputFolder: "出力フォルダ",
    sameFolder: "元のフォルダと同じ",
    chooseOutput: "出力フォルダを選択",
    useSourceFolders: "元のフォルダを使用",
    folders: "フォルダ",
    convert: "変換",
    output: "出力結果",
    downloadAll: "すべてダウンロード",
    noFilesSelected: "ファイルが選択されていません",
    download: "ダウンロード",
    pending: "保留中",
    input: "入力",
    markdown: "Markdown",
    copy: "コピー",
    save: "保存",
    madeBy: "作成者:",
    githubRepo: "オープンソース - GitHub リポジトリ",
    variants: "その他のバリアント",
    webApp: "Web アプリケーション",
    webAppVariantDetail: "GitHub Pages でブラウザ版を開きます。",
    desktopApp: "デスクトップアプリケーション",
    desktopApplication: "デスクトップアプリケーション",
    desktopVariantDetail: "リリースページを開き、デバイスに合う Windows、macOS、Linux のファイルを選びます。",
    openVsxVariantDetail: "Open VSX 対応エディターにインストールします。",
    vscodeMarketplace: "VS Code Marketplace",
    vscodeMarketplaceVariantDetail: "Visual Studio Code に直接インストールします。",
    npmPackage: "npm パッケージ",
    npmPackageVariantDetail: "スクリプトやアプリで Node.js パッケージとして使用します。",
    updateAvailable: "更新があります",
    mitLicense: "MIT ライセンス",
    privacyPolicy: "プライバシーポリシー",
    termsOfService: "利用規約",
    backToConverter: "変換器に戻る",
    returnToConverter: "変換器に戻る",
    lastUpdated: "最終更新日: 2026年6月",
    copiedNotice: "コピーしました",
    savedNotice: "保存しました",
    privacyNoticeHeader: "100% クライアント側＆ローカル処理",
    privacyNoticeText: "Markdown Them は、完全にローカルデバイス上で動作するように設計されています。ファイルをアップロードしたり、データを追跡したり、外部サーバーに情報を送信したりすることは一切ありません。",
    privacySec1Title: "1. 収集する情報",
    privacySec1Intro: "お客様のデータはお客様だけのものと確信しております。そのため：",
    noFileCollection: "ファイルの非収集",
    noFileCollectionDetail: "文書（DOCX, PDF, HTML, XLSX, PPTX, 等）やテキストを Markdown に変換する際、すべての処理はウェブブラウザ内またはローカルコンピューター内で完結します。ファイルが外部へ送信されることはありません。",
    noPersonalData: "個人データの非収集",
    noPersonalDataDetail: "アカウントの作成、登録、サインアップは必要ありません。お名前、メールアドレス、その他の識別情報は一切収集しません。",
    noTelemetry: "テレメトリや追跡の非搭載",
    noTelemetryDetail: "アプリはお客様の行動を追跡するスクリプト、分析ツール、cookie を含んでいません。",
    privacySec2Title: "2. 設定情報の保存",
    privacySec2Text: "使いやすさを向上させるため、お客様のテーマ設定等のユーザー設定をブラウザの localStorage にローカル保存します。このデータは端末内のみに留まり、外部同期されません。ブラウザのデータを削除すればいつでも消去可能です。",
    privacySec3Title: "3. サードパーティ製ウェブサイトとサービス",
    privacySec3Text: "当アプリは GitHub や npm などの外部サイトへのリンクを含む場合があります。これらの外部サイトは当方が運営しているものではなく、独自のポリシーを持っています。訪問先サイトのポリシーを確認することをお勧めします。",
    privacySec4Title: "4. プライバシーポリシーの変更について",
    privacySec4Text: "プライバシーポリシーは必要に応じて更新される場合があります。変更があった場合はこのページに掲載し、更新日を改訂します。",
    privacySec5Title: "5. お問い合わせ",
    privacySec5Text: "プライバシーポリシーに関するご質問やご提案がございましたら、プロジェクトのリポジトリよりお気軽にお問い合わせください。",
    termsNoticeHeader: "MITライセンスによるオープンソース",
    termsNoticeText: "Markdown Them は完全にオープンソースです。MITライセンスの条項に従って、このソフトウェアを自由に利用、修正、配布できます。",
    termsSec1Title: "1. 利用規約への同意",
    termsSec1Text: "Markdown Them のウェブ版またはデスクトップ版を利用することにより、本規約に同意したものとみなされます。すべての条件に同意できない場合は、アプリの使用を中止してください。",
    termsSec2Title: "2. ライセンスと許可される使用範囲",
    termsSec2Intro: "Markdown Them は MIT ライセンスの下でライセンスされています。以下の行為が許可されます：",
    termsSec2Item1: "商業プロジェクトまたは個人プロジェクトでのソフトウェアの使用。",
    termsSec2Item2: "ソフトウェアのコピーの変更、配布、およびサブライセンス。",
    termsSec2Item3: "他のパッケージまたは配布物に本ソフトウェアを含めること。",
    termsSec2Outro: "唯一の要件は、著作権表示および許諾表示をソフトウェアのすべてのコピーまたは実質的な部分に含めることです。",
    termsSec3Title: "3. ローカル処理の制限",
    termsSec3Text: "Markdown Them はクライアント側変換ツールとして設計されています。「現状有姿」で提供され、オフライン/ローカルでの使用を前提としています。変換器に読み込むファイルの安全性と完全性の確保は、お客様自身の責任となります。",
    termsSec4Title: "4. 保証の否認",
    termsSec4Text: "本ソフトウェアは「現状有姿」で提供され、商品性、特定目的への適合性、非侵害性を含め、明示・黙示を問わずいかなる保証もありません。著者または著作権者は、いかなる請求、損害、またはその他の責任に対しても責任を負いません。",
    termsSec5Title: "5. 利用規約の変更",
    termsSec5Text: "当方は独自の裁量により、いつでも本規約を変更または修正する権利を有します。変更について定期的に本規約を確認することは、利用者の責任となります。",
  },
  no: {
    appName: "Markdown Them",
    tagline: "Konverter fra DOCX, DOC, PDF, HTML, XLSX, XLS, XLM, PPTX, ODT, ODP, ODS, RTF og tekstfiler til lesbar markdown. Merk: Eldre formater (.doc, .xls, .xlm) bruker emulert filnavnendring, og konverteringen vil av og til ikke fungere korrekt.",
    files: "Filer",
    text: "Tekst",
    privacyFirst: "Personvern først",
    privacyFirstDetail: "Ingen konto, ingen filsporing, ingen telemetri",
    localProcessingDesktop: "100% lokal behandling",
    localProcessingDesktopDetail: "Kjører på denne datamaskinen",
    localProcessingBrowser: "100% klientsidekonvertering",
    localProcessingBrowserDetail: "Kjører bare inne i nettleseren din, og bare konverteringsprosesser",
    noUploads: "Ingen filopplasting",
    noUploadsDetail: "Filer forlater aldri enheten din, ingen kan hente filene dine",
    selection: "Utvalg",
    clear: "Tøm",
    selected: "valgt",
    done: "fullført",
    failed: "mislyktes",
    outputFolder: "Utdatamappe",
    sameFolder: "Samme mappe som kilde",
    chooseOutput: "Velg utdatamappe",
    useSourceFolders: "Bruk kildemapper",
    folders: "Mapper",
    convert: "Konverter",
    output: "Utdata",
    downloadAll: "Last ned alle",
    noFilesSelected: "Ingen filer valgt",
    download: "Last ned",
    pending: "venter",
    input: "Inndata",
    markdown: "Markdown",
    copy: "Kopier",
    save: "Lagre",
    madeBy: "laget av",
    githubRepo: "Åpen kildekode - GitHub-depot",
    variants: "Andre varianter",
    webApp: "Webapplikasjon",
    webAppVariantDetail: "Åpne nettleserversjonen på GitHub Pages.",
    desktopApp: "Skrivebordsapplikasjon",
    desktopApplication: "Skrivebordsapplikasjon",
    desktopVariantDetail: "Åpne utgivelser og velg Windows-, macOS- eller Linux-filen som passer enheten din.",
    openVsxVariantDetail: "Installer i Open VSX-kompatible editorer.",
    vscodeMarketplace: "VS Code Marketplace",
    vscodeMarketplaceVariantDetail: "Installer direkte i Visual Studio Code.",
    npmPackage: "npm-pakke",
    npmPackageVariantDetail: "Bruk Node.js-pakken i skript eller apper.",
    updateAvailable: "Oppdatering tilgjengelig",
    mitLicense: "MIT-lisens",
    privacyPolicy: "Personvernserklæring",
    termsOfService: "Vilkår for bruk",
    backToConverter: "Tilbake til konverterer",
    returnToConverter: "Gå tilbake til konverterer",
    lastUpdated: "Sist oppdatert: Juni 2026",
    copiedNotice: "Kopiert",
    savedNotice: "Lagret",
    privacyNoticeHeader: "100% klientside og lokal behandling",
    privacyNoticeText: "Markdown Them er utviklet for å kjøre helt på din lokale enhet. Vi laster aldri opp filene dine, sporer ikke dataene dine, og overfører ikke informasjon til eksterne servere.",
    privacySec1Title: "1. Informasjon vi samler inn",
    privacySec1Intro: "Vi mener at dine data tilhører deg alene. På grunn av dette:",
    noFileCollection: "Ingen filinnsamling",
    noFileCollectionDetail: "Når du konverterer dokumenter (DOCX, PDF, HTML, XLSX, PPTX, etc.) eller tekst til Markdown, utføres all behandling lokalt i nettleseren din eller på din lokale datamaskin. Filene dine forlater aldri enheten din.",
    noPersonalData: "Ingen personopplysninger",
    noPersonalDataDetail: "Vi krever ikke opprettelse av konto, registrering eller pålogging. Vi samler ikke inn navn, e-postadresser eller annen identifiserende informasjon.",
    noTelemetry: "Ingen telemetri eller sporing",
    noTelemetryDetail: "Applikasjonen inneholder ikke sporingsskript, analyseverktøy eller informasjonskapsler for å spore atferden din.",
    privacySec2Title: "2. Lagring av innstillinger",
    privacySec2Text: "For å gi en sømløs opplevelse lagrer vi brukerinnstillinger (som foretrukket fargetema) lokalt i nettleserens localStorage. Disse dataene forblir på maskinen din og synkroniseres aldri med en ekstern tjeneste. Du kan slette disse dataene når som helst ved å tømme nettleserens lagring.",
    privacySec3Title: "3. Tredjeparts nettsteder og tjenester",
    privacySec3Text: "Vår applikasjon kan koble til eksterne nettsteder som GitHub eller npm. Disse eksterne nettstedene drives ikke av oss og har sine egne personvernregler. Vi råder deg til å lese personvernreglene for alle tredjeparts nettsteder du besøker.",
    privacySec4Title: "4. Endringer i denne personvernerklæringen",
    privacySec4Text: "Vi kan oppdatere personvernerklæringen vår fra tid til annen. Eventuelle endringer vil bli lagt ut på denne siden med en oppdatert revisjonsdato.",
    privacySec5Title: "5. Kontakt oss",
    privacySec5Text: "Hvis du har spørsmål eller forslag angående personvernerklæringen vår, kan du kontakte oss på prosjektets GitHub-depot.",
    termsNoticeHeader: "Åpen kildekode under MIT-lisensen",
    termsNoticeText: "Markdown Them er helt åpen kildekode. Du står fritt til å bruke, endre og distribuere denne programvaren i samsvar med vilkårene i MIT-lisensen.",
    termsSec1Title: "1. Aksept av vilkår",
    termsSec1Text: "Ved å besøke eller bruke Markdown Them web- eller skrivebordsapplikasjon, godtar du å være bundet av disse vilkårene for bruk. Hvis du ikke godtar alle vilkårene og betingelsene, må du ikke bruke applikasjonen.",
    termsSec2Title: "2. Lisens og tillatt bruk",
    termsSec2Intro: "Markdown Them er lisensiert under vilkårene i MIT-lisensen. Du får tillatelse til å:",
    termsSec2Item1: "Bruke programvaren til kommersielle eller personlige prosjekter.",
    termsSec2Item2: "Endre, distribuere og viderelisensiere kopier av programvaren.",
    termsSec2Item3: "Inkludere programvaren i andre pakker eller distribusjoner.",
    termsSec2Outro: "Det eneste kravet er at opphavsrettsmerknaden og lisensmerknaden må være inkludert i alle kopier eller vesentlige deler av programvaren.",
    termsSec3Title: "3. Begrensning av lokal behandling",
    termsSec3Text: "Markdown Them er utformet som et klientsidekonverteringsverktøy. Det leveres \"som det er\", beregnet for offline/lokal bruk. Du er selv ansvarlig for å sikre sikkerheten og integriteten til filene du importerer.",
    termsSec4Title: "4. Garantifraskrivelse",
    termsSec4Text: "PROGRAMVAREN LEVERES \"SOM DEN ER\", UTEN NOEN FORM FOR GARANTI, UTTRYKT ELLER UNDERFORSTÅTT. UNDER INGEN OMSTENDIGHETER SKAL FORFATTERNE ELLER OPPHAVSRETTSHAVE NE RETTSLIG ANSVARLIG FOR NOE KRAV, SKADE ELLER ANDRE FORPLIKTELSER.",
    termsSec5Title: "5. Endringer i vilkårene",
    termsSec5Text: "Vi forbeholder oss retten til, etter eget skjønn, å endre eller erstatte disse vilkårene når som helst. Det er ditt ansvar å sjekke disse vilkårene med jevne mellomrom for endringer.",
  },
  es: {
    appName: "Markdown Them",
    tagline: "Convierta archivos DOCX, DOC, PDF, HTML, XLSX, XLS, XLM, PPTX, ODT, ODP, ODS, RTF y de texto a un formato markdown legible. Nota: Los formatos heredados (.doc, .xls, .xlm) usan emulación de cambio de nombre y a veces no se convertirán correctamente.",
    files: "Archivos",
    text: "Texto",
    privacyFirst: "Privacidad primero",
    privacyFirstDetail: "Sin cuenta, sin seguimiento de archivos, sin telemetría",
    localProcessingDesktop: "Procesamiento 100% local",
    localProcessingDesktopDetail: "Se ejecuta en este ordenador",
    localProcessingBrowser: "Conversión 100% en el cliente",
    localProcessingBrowserDetail: "Se ejecuta solo en su navegador, y solo procesos de conversión",
    noUploads: "Sin subir documentos",
    noUploadsDetail: "Los archivos nunca salen de su dispositivo, nadie puede obtener sus archivos",
    selection: "Selección",
    clear: "Limpiar",
    selected: "seleccionados",
    done: "completados",
    failed: "fallidos",
    outputFolder: "Carpeta de salida",
    sameFolder: "Misma carpeta que el origen",
    chooseOutput: "Elegir carpeta de salida",
    useSourceFolders: "Usar carpetas de origen",
    folders: "Carpetas",
    convert: "Convertir",
    output: "Resultado",
    downloadAll: "Descargar todo",
    noFilesSelected: "Ningún archivo seleccionado",
    download: "Descargar",
    pending: "pendiente",
    input: "Entrada",
    markdown: "Markdown",
    copy: "Copiar",
    save: "Guardar",
    madeBy: "hecho por",
    githubRepo: "Código abierto - Repositorio de GitHub",
    variants: "Otras variantes",
    webApp: "Aplicación web",
    webAppVariantDetail: "Abre la versión de navegador en GitHub Pages.",
    desktopApp: "Aplicación de escritorio",
    desktopApplication: "Aplicación de escritorio",
    desktopVariantDetail: "Abre la página de lanzamientos y elige el archivo de Windows, macOS o Linux adecuado para tu dispositivo.",
    openVsxVariantDetail: "Instala en editores compatibles con Open VSX.",
    vscodeMarketplace: "VS Code Marketplace",
    vscodeMarketplaceVariantDetail: "Instala directamente en Visual Studio Code.",
    npmPackage: "Paquete npm",
    npmPackageVariantDetail: "Usa el paquete de Node.js en scripts o aplicaciones.",
    updateAvailable: "Actualización disponible",
    mitLicense: "Licencia MIT",
    privacyPolicy: "Política de privacidad",
    termsOfService: "Condiciones de servicio",
    backToConverter: "Volver al convertidor",
    returnToConverter: "Volver al convertidor",
    lastUpdated: "Última actualización: Junio de 2026",
    copiedNotice: "Copiado",
    savedNotice: "Guardado",
    privacyNoticeHeader: "Procesamiento 100% local y en el cliente",
    privacyNoticeText: "Markdown Them está diseñado para ejecutarse completamente en su dispositivo local. Nunca subimos sus archivos, rastreamos sus datos ni transmitimos información a servidores externos.",
    privacySec1Title: "1. Información que recopilamos",
    privacySec1Intro: "Creemos que sus datos son únicamente suyos. Por ello:",
    noFileCollection: "Sin recopilación de archivos",
    noFileCollectionDetail: "Al convertir documentos (DOCX, PDF, HTML, XLSX, PPTX, etc.) o texto a Markdown, todo el procesamiento se realiza localmente dentro de su navegador web u ordenador local. Sus archivos nunca salen de su dispositivo.",
    noPersonalData: "Sin datos personales",
    noPersonalDataDetail: "No requerimos creación de cuenta, registro ni inicio de sesión. No recopilamos nombres, direcciones de correo electrónico ni otra información de identificación.",
    noTelemetry: "Sin telemetría ni seguimiento",
    noTelemetryDetail: "La aplicación no contiene scripts de seguimiento, herramientas de análisis ni cookies para seguir su comportamiento.",
    privacySec2Title: "2. Almacenamiento de configuraciones",
    privacySec2Text: "Para proporcionar una experiencia fluida, almacenamos las preferencias del usuario (como el tema de color preferido) localmente en el localStorage de su navegador. Estos datos permanecen en su máquina y nunca se sincronizan con un servicio externo. Puede borrar estos datos en cualquier momento limpiando el almacenamiento de su navegador.",
    privacySec3Title: "3. Sitios web y servicios de terceros",
    privacySec3Text: "Nuestra aplicación puede enlazar a sitios web externos como GitHub o npm. Estos sitios externos no son operados por nosotros y tienen sus propias políticas de privacidad. Le aconsejamos que revise la política de privacidad de cualquier sitio web de terceros que visite.",
    privacySec4Title: "4. Cambios en esta política de privacidad",
    privacySec4Text: "Es posible que actualicemos nuestra política de privacidad de vez en cuando. Cualquier cambio se publicará en esta página con una fecha de revisión actualizada.",
    privacySec5Title: "5. Contacto",
    privacySec5Text: "Si tiene alguna pregunta o sugerencia sobre nuestra Política de privacidad, no dude en contactarnos a través del repositorio de nuestro proyecto.",
    termsNoticeHeader: "Código abierto bajo la Licencia MIT",
    termsNoticeText: "Markdown Them es completamente de código abierto. Es libre de usar, modificar y distribuir este software de acuerdo con los términos de la Licencia MIT.",
    termsSec1Title: "1. Aceptación de las condiciones",
    termsSec1Text: "Al acceder o utilizar la aplicación web o de escritorio de Markdown Them, usted acepta estar sujeto a estas Condiciones de servicio. Si no está de acuerdo con todos los términos y condiciones, no utilice la aplicación.",
    termsSec2Title: "2. Licencia y uso permitido",
    termsSec2Intro: "Markdown Them está licenciado bajo los términos de la Licencia MIT. Se le concede permiso para:",
    termsSec2Item1: "Utilizar el software para proyectos comerciales o personales.",
    termsSec2Item2: "Modificar, distribuir y sublicenciar copias del software.",
    termsSec2Item3: "Incluir el software en otros paquetes o distribuciones.",
    termsSec2Outro: "El único requisito es que el aviso de derechos de autor y el aviso de licencia se incluyan en todas las copias o partes sustanciales del Software.",
    termsSec3Title: "3. Limitación del procesamiento local",
    termsSec3Text: "Markdown Them está diseñado como una herramienta de conversión en el cliente. Se proporciona \"tal cual\", destinada a un uso local o sin conexión. Usted es el único responsable de garantizar la seguridad y la integridad de los archivos que importa.",
    termsSec4Title: "4. Exclusión de garantías",
    termsSec4Text: "EL SOFTWARE SE PROPORCIONA \"TAL CUAL\", SIN GARANTÍA DE NINGÚN TIPO, EXPRESA O IMPLÍCITA. EN NINGÚN CASO LOS AUTORES O TITULARES DE LOS DERECHOS DE AUTOR SERÁN RESPONSABLES DE NINGUNA RECLAMACIÓN, DAÑO U OTRA RESPONSABILIDAD.",
    termsSec5Title: "5. Cambios en las condiciones",
    termsSec5Text: "Nos reservamos el derecho, a nuestra entera discreción, de modificar o reemplazar estas Condiciones en cualquier momento. Es su responsabilidad revisar estas Condiciones periódicamente para ver si hay cambios.",
  },
  fr: {
    appName: "Markdown Them",
    tagline: "Convertissez les fichiers DOCX, DOC, PDF, HTML, XLSX, XLS, XLM, PPTX, ODT, ODP, ODS, RTF et texte en markdown lisible. Note : Les formats hérités (.doc, .xls, .xlm) utilisent une émulation de renommage et peuvent parfois ne pas se convertir correctement.",
    files: "Fichiers",
    text: "Texte",
    privacyFirst: "Confidentialité d'abord",
    privacyFirstDetail: "Sans compte, sans suivi de fichiers, sans télémétrie",
    localProcessingDesktop: "Traitement 100% local",
    localProcessingDesktopDetail: "S'exécute sur cet ordinateur",
    localProcessingBrowser: "Conversion 100% côté client",
    localProcessingBrowserDetail: "S'exécute uniquement dans votre navigateur, processus de conversion interne",
    noUploads: "Pas de téléversement",
    noUploadsDetail: "Les fichiers ne quittent jamais votre appareil, personne ne peut y accéder",
    selection: "Sélection",
    clear: "Effacer",
    selected: "sélectionnés",
    done: "terminés",
    failed: "échoués",
    outputFolder: "Dossier de sortie",
    sameFolder: "Même dossier que la source",
    chooseOutput: "Choisir le dossier de sortie",
    useSourceFolders: "Utiliser les dossiers source",
    folders: "Dossiers",
    convert: "Convertir",
    output: "Sortie",
    downloadAll: "Tout télécharger",
    noFilesSelected: "Aucun fichier sélectionné",
    download: "Télécharger",
    pending: "en attente",
    input: "Entrée",
    markdown: "Markdown",
    copy: "Copier",
    save: "Enregistrer",
    madeBy: "fait par",
    githubRepo: "Open source - Dépôt GitHub",
    variants: "Autres variantes",
    webApp: "Application web",
    webAppVariantDetail: "Ouvre la version navigateur sur GitHub Pages.",
    desktopApp: "Application de bureau",
    desktopApplication: "Application de bureau",
    desktopVariantDetail: "Ouvre la page des versions et choisis le fichier Windows, macOS ou Linux adapté à ton appareil.",
    openVsxVariantDetail: "Installe dans les éditeurs compatibles Open VSX.",
    vscodeMarketplace: "VS Code Marketplace",
    vscodeMarketplaceVariantDetail: "Installe directement dans Visual Studio Code.",
    npmPackage: "Package npm",
    npmPackageVariantDetail: "Utilise le package Node.js dans des scripts ou des applications.",
    updateAvailable: "Mise à jour disponible",
    mitLicense: "Licence MIT",
    privacyPolicy: "Politique de confidentialité",
    termsOfService: "Conditions d'utilisation",
    backToConverter: "Retour au convertisseur",
    returnToConverter: "Retour au convertisseur",
    lastUpdated: "Dernière mise à jour : Juin 2026",
    copiedNotice: "Copié",
    savedNotice: "Enregistré",
    privacyNoticeHeader: "Traitement 100% local et côté client",
    privacyNoticeText: "Markdown Them est conçu pour s'exécuter entièrement sur votre appareil local. Nous ne téléversons jamais vos fichiers, ne suivons pas vos données et ne transmettons aucune information vers des serveurs externes.",
    privacySec1Title: "1. Informations que nous collectons",
    privacySec1Intro: "We believe that your data is yours alone. Because of this:",
    noFileCollection: "Aucune collecte de fichiers",
    noFileCollectionDetail: "Lorsque vous convertissez des documents (DOCX, PDF, HTML, XLSX, PPTX, etc.) ou du texte en Markdown, tous les traitements sont effectués localement dans votre navigateur web ou votre ordinateur local. Vos fichiers ne quittent jamais votre appareil.",
    noPersonalData: "Aucune donnée personnelle",
    noPersonalDataDetail: "Nous ne requérons ni création de compte, ni enregistrement, ni connexion. Nous ne collectons pas de noms, d'adresses e-mail ou d'autres informations d'identification.",
    noTelemetry: "Pas de télémétrie ni de suivi",
    noTelemetryDetail: "L'application ne contient aucun script de suivi, outil d'analyse ou cookie pour suivre votre comportement.",
    privacySec2Title: "2. Stockage des paramètres",
    privacySec2Text: "Pour offrir une expérience fluide, nous stockons les préférences de l'utilisateur (comme le thème de couleur préféré) localement dans le localStorage de votre navigateur. Ces données restent sur votre machine et ne sont jamais synchronisées avec un service externe. Vous pouvez effacer ces données à tout moment en vidant le stockage de votre navigateur.",
    privacySec3Title: "3. Sites web et services tiers",
    privacySec3Text: "Notre application peut lier vers des sites web externes comme GitHub ou npm. Ces sites externes ne sont pas gérés par nous et ont leurs propres politiques de confidentialité. Nous vous conseillons de consulter la politique de confidentialité de tous les sites tiers que vous visitez.",
    privacySec4Title: "4. Modification de cette politique de confidentialité",
    privacySec4Text: "We may update our Privacy Policy from time to time. Any changes will be posted on this page with an updated revision date.",
    privacySec5Title: "5. Nous contacter",
    privacySec5Text: "Si vous avez des questions ou des suggestions concernant notre Politique de confidentialité, n'hésitez pas à nous contacter via le dépôt de notre projet.",
    termsNoticeHeader: "Open source sous licence MIT",
    termsNoticeText: "Markdown Them est entièrement open source. Vous êtes libre d'utiliser, de modifier et de distribuer ce logiciel conformément aux termes de la licence MIT.",
    termsSec1Title: "1. Acceptation des conditions",
    termsSec1Text: "En accédant à ou en utilisant l'application web ou de bureau Markdown Them, vous acceptez d'être lié par ces Conditions d'utilisation. Si vous n'acceptez pas toutes les conditions, n'utilisez pas l'application.",
    termsSec2Title: "2. Licence et utilisation autorisée",
    termsSec2Intro: "Markdown Them est sous licence MIT. Vous êtes autorisé à :",
    termsSec2Item1: "Utiliser le logiciel pour des projets commerciaux ou personnels.",
    termsSec2Item2: "Modifier, distribuer et sous-licencier des copies du logiciel.",
    termsSec2Item3: "Inclure le logiciel dans d'autres packages ou distributions.",
    termsSec2Outro: "La seule exigence est que l'avis de droit d'auteur et l'avis de licence soient inclus dans toutes les copies ou parties substantielles du logiciel.",
    termsSec3Title: "3. Limite du traitement local",
    termsSec3Text: "Markdown Them est conçu comme un outil de conversion côté client. Il est fourni \"en l'état\", destiné à un usage hors ligne/local. Vous êtes seul responsable d'assurer la sécurité et l'intégrité des fichiers que vous importez.",
    termsSec4Title: "4. Exclusion de garantie",
    termsSec4Text: "LE LOGICIEL EST FOURNI \"EN L'ÉTAT\", SANS GARANTIE D'AUCUNE SORTE, EXPRESSE OU IMPLICITE. EN AUCUN CAS LES AUTEURS OU TITULAIRES DE DROITS D'AUTEUR NE SERONT RESPONSABLES DE TOUTE RÉCLAMATION, DOMMAGE OU AUTRE RESPONSABILITÉ.",
    termsSec5Title: "5. Modification des conditions",
    termsSec5Text: "Nous nous réservons le droit, à notre seule discrétion, de modifier ou de remplacer ces Conditions à tout moment. Il vous incombe de consulter périodiquement ces Conditions pour prendre connaissance des changements.",
  },
  ko: {
    appName: "Markdown Them",
    tagline: "DOCX, DOC, PDF, HTML, XLSX, XLS, XLM, PPTX, ODT, ODP, ODS, RTF 및 텍스트 파일을 읽기 쉬운 markdown으로 변환합니다. 참고: 레거시 형식(.doc, .xls, .xlm)은 이름 변경 에뮬레이션을 사용하므로 가끔 올바르게 변환되지 않을 수 있습니다.",
    files: "파일",
    text: "텍스트",
    privacyFirst: "개인정보 보호 우선",
    privacyFirstDetail: "계정 없음, 파일 추적 없음, 원격 측정 없음",
    localProcessingDesktop: "100% 로컬 처리",
    localProcessingDesktopDetail: "이 컴퓨터에서 실행",
    localProcessingBrowser: "100% 클라이언트 측 변환",
    localProcessingBrowserDetail: "브라우저 내부에서만 실행되며, 변환 프로세스만 수행",
    noUploads: "문서 업로드 없음",
    noUploadsDetail: "파일이 기기를 절대 떠나지 않으며, 누구도 파일에 액세스할 수 없습니다",
    selection: "선택",
    clear: "지우기",
    selected: "개 선택됨",
    done: "성공",
    failed: "실패",
    outputFolder: "출력 폴더",
    sameFolder: "원본 파일과 동일한 폴더",
    chooseOutput: "출력 폴더 선택",
    useSourceFolders: "원본 폴더 사용",
    folders: "폴더",
    convert: "변환",
    output: "출력 결과",
    downloadAll: "모두 다운로드",
    noFilesSelected: "선택된 파일 없음",
    download: "다운로드",
    pending: "대기 중",
    input: "입력",
    markdown: "Markdown",
    copy: "복사",
    save: "저장",
    madeBy: "제작:",
    githubRepo: "오픈 소스 - GitHub 저장소",
    variants: "다른 버전",
    webApp: "웹 애플리케이션",
    webAppVariantDetail: "GitHub Pages에서 브라우저 버전을 엽니다.",
    desktopApp: "데스크톱 애플리케이션",
    desktopApplication: "데스크톱 애플리케이션",
    desktopVariantDetail: "릴리스 페이지를 열고 기기에 맞는 Windows, macOS 또는 Linux 파일을 선택합니다.",
    openVsxVariantDetail: "Open VSX 호환 에디터에 설치합니다.",
    vscodeMarketplace: "VS Code Marketplace",
    vscodeMarketplaceVariantDetail: "Visual Studio Code에 직접 설치합니다.",
    npmPackage: "npm 패키지",
    npmPackageVariantDetail: "스크립트나 앱에서 Node.js 패키지로 사용합니다.",
    updateAvailable: "업데이트 가능",
    mitLicense: "MIT 라이선스",
    privacyPolicy: "개인정보 처리방침",
    termsOfService: "서비스 약관",
    backToConverter: "변환기로 돌아가기",
    returnToConverter: "변환기로 돌아가기",
    lastUpdated: "최종 업데이트: 2026년 6월",
    copiedNotice: "복사됨",
    savedNotice: "저장됨",
    privacyNoticeHeader: "100% 클라이언트 측 및 로컬 처리",
    privacyNoticeText: "Markdown Them은 완전하게 귀하의 로컬 기기에서 실행되도록 설계되었습니다. 귀하의 파일을 절대 업로드하지 않으며, 데이터를 추적하거나 외부 서버로 정보를 전송하지 않습니다.",
    privacySec1Title: "1. 수집하는 정보",
    privacySec1Intro: "우리는 귀하의 데이터가 귀하만의 것이라고 확신합니다. 그렇기 때문에:",
    noFileCollection: "파일 수집 없음",
    noFileCollectionDetail: "귀하가 문서(DOCX, PDF, HTML, XLSX, PPTX, 등) 또는 텍스트를 Markdown으로 변환할 때, 모든 처리는 웹 브라우저나 로컬 컴퓨터 내부에서 로컬로 실행됩니다. 귀하의 파일은 기기를 절대 떠나지 않습니다.",
    noPersonalData: "개인 데이터 없음",
    noPersonalDataDetail: "우리는 계정 생성, 등록 또는 가입을 요구하지 않습니다. 우리는 이름, 이메일 주소 또는 기타 식별 정보를 수집하지 않습니다.",
    noTelemetry: "원격 측정 또는 추적 없음",
    noTelemetryDetail: "이 어플리케이션은 귀하의 행동을 추적하는 추적 스크립트, 분석 도구 또는 쿠키를 포함하지 않습니다.",
    privacySec2Title: "2. 설정 저장",
    privacySec2Text: "원활한 경험을 제공하기 위해, 귀하의 사용자 환경설정(예: 선호하는 색상 테마)을 브라우저의 localStorage에 로컬로 저장합니다. 이 데이터는 귀하의 기기에만 남아있으며 외부 서비스와 동기화되지 않습니다. 브라우저 저장소를 비워 언제든지 이 데이터를 지울 수 있습니다.",
    privacySec3Title: "3. 타사 웹사이트 및 서비스",
    privacySec3Text: "우리 어플리케이션은 GitHub 또는 npm과 같은 외부 웹사이트에 연결될 수 있습니다. 이러한 외부 사이트는 우리가 운영하지 않으며 자체적인 개인정보 보호정책을 가지고 있습니다. 귀하가 방문하는 모든 타사 웹사이트의 개인정보 보호정책을 검토할 것을 권장합니다.",
    privacySec4Title: "4. 개인정보 처리방침의 변경",
    privacySec4Text: "우리는 때때로 개인정보 처리방침을 업데이트할 수 있습니다. 변경 사항은 업데이트된 개정 날짜와 함께 이 페이지에 게시됩니다.",
    privacySec5Title: "5. 문의하기",
    privacySec5Text: "개인정보 처리방침에 관하여 질문이나 제안이 있으신 경우, 언제든지 우리 프로젝트 저장소로 연락해 주시기 바랍니다.",
    termsNoticeHeader: "MIT 라이선스에 따른 오픈 소스",
    termsNoticeText: "Markdown Them은 완전한 오픈 소스입니다. MIT 라이선스 조항에 따라 이 소프트웨어를 자유롭게 사용, 수정 및 배포할 수 있습니다.",
    termsSec1Title: "1. 약관의 수동 동의",
    termsSec1Text: "Markdown Them 웹 어플리케이션 또는 데스크톱 어플리케이션에 액세스하거나 사용함으로써 귀하는 이 서비스 약관에 동의하게 됩니다. 모든 약관과 조건에 동의하지 않는 경우 어플리케이션을 사용하지 마십시오.",
    termsSec2Title: "2. 라이선스 및 사용 허가 범위",
    termsSec2Intro: "Markdown Them은 MIT 라이선스 조건에 따라 제공됩니다. 귀하는 다음 권한을 허가받습니다:",
    termsSec2Item1: "상업적 또는 개인 프로젝트에 소프트웨어 사용.",
    termsSec2Item2: "소프트웨어 복제본 수정, 배포 및 하위 라이선스 부여.",
    termsSec2Item3: "소프트웨어를 다른 패키지나 배포판에 포함.",
    termsSec2Outro: "유일한 요구 사항은 저작권 고지 및 라이선스 고지가 소프트웨어의 모든 사본 또는 실질적인 부분에 포함되어야 한다는 것입니다.",
    termsSec3Title: "3. 로컬 처리 한계",
    termsSec3Text: "Markdown Them은 클라이언트 측 변환 도구로 설계되었습니다. 오프라인/로컬 사용을 목적으로 \"있는 그대로\" 제공됩니다. 귀하가 변환기에 가져오는 파일의 안전성과 무결성을 확보할 책임은 전적으로 귀하에게 있습니다.",
    termsSec4Title: "4. 보증 부인",
    termsSec4Text: "소프트웨어는 상품성, 특정 목적에의 적합성 및 비침해에 대한 보증을 포함하여 명시적이거나 묵시적인 어떠한 종류의 보증도 없이 \"있는 그대로\" 제공됩니다. 어떠한 경우에도 저자 또는 저작권자는 어떠한 청구, 손해 또는 책임에 대해서도 책임을 지지 않습니다.",
    termsSec5Title: "5. 약관의 변경",
    termsSec5Text: "우리는 독자적인 재량에 따라 언제든지 이 약관을 수정하거나 변경할 수 있는 권리를 보유합니다. 변경 사항에 대해 정기적으로 이 약관을 확인할 책임은 귀하에게 있습니다.",
  },
};

interface LanguageContextProps {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = "markdown-them-language";

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    if (typeof window !== "undefined") {
      const saved = window.localStorage.getItem(LANGUAGE_STORAGE_KEY) as LanguageCode;
      if (saved && translations[saved]) {
        return saved;
      }
      // Detect browser language
      const navLang = window.navigator.language.split("-")[0] as LanguageCode;
      if (navLang && translations[navLang]) {
        return navLang;
      }
    }
    return "en";
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    if (typeof window !== "undefined") {
      window.localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
    }
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations["en"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
